import "./globals.css";
import { Header } from "./_components/header";
import NextUIWrapper from "./NextWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="antialiased bg-gradient-to-b from-black to-lime-800 min-h-screen">
        <NextUIWrapper>
          <Header />
          <main className="min-h-[calc(100vh-72px)] mt-10 w-[65%] mx-auto justify-center flex">
            {children}
          </main>
          <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center"></footer>
        </NextUIWrapper>
      </body>
    </html>
  );
}